spring.cloud.stream:
  bindings:
    domainProcessor-out-0:
      destination: my-domains
  kafka:
    bindings:
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092

