spring.cloud.stream:
  function:
    definition: consumer
  bindings:
    consumer-in-0:
      destination: "com.example.domains.new2"
  kafka:
    bindings:
      consumer-in-0:
        consumer:
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringSerializer
            value:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092