spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        schema:
          registry:
            url: "https://psrc-mw731.us-east-2.aws.confluent.cloud"
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: "PTGIP2PWT24RUGYC:S2CKraGQPm2PDrosgdxoa13rzGGh7E6clmqKGHnWpLmMoi2djE570hOAGdCV1V95"
        specific:
          avro:
            reader: "true"
avro:
  topic:
    name: "com.example.domains.new2"
