spring:
  kafka:
    bootstrap-servers: "pkc-ymrq7.us-east-2.aws.confluent.cloud:9092"
    consumer:
      group-id: "spring-boot-avro-consumer-id"
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      autoOffsetReset: "earliest"
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='VKORYZIIOTAQGEIN' password='NLhmfnvzqLOpJ3qccSZiVtvkuzhXS70DbbxgJc1uT284J6b5YQbkLl22PiC/zxDm';"
        schema:
          registry:
            url: "https://psrc-mw731.us-east-2.aws.confluent.cloud"
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: "PTGIP2PWT24RUGYC:S2CKraGQPm2PDrosgdxoa13rzGGh7E6clmqKGHnWpLmMoi2djE570hOAGdCV1V95"
        specific:
          avro:
            reader: "true"
avro:
  topic:
    name: "com.example.films"
