spring.cloud.stream:
  function:
    definition: domainService
  bindings:
    domainService-in-0:
      destination: "com.example.domains"
  kafka:
    bindings:
      domainService-in-0:
        consumer:
          configuration:
            value:
              deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092