server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: "https://psrc-mw731.us-east-2.aws.confluent.cloud"
        basic.auth.credentials.source: USER_INFO
        basic.auth.user.info: "PTGIP2PWT24RUGYC:S2CKraGQPm2PDrosgdxoa13rzGGh7E6clmqKGHnWpLmMoi2djE570hOAGdCV1V95"

avro:
  topic:
    name: "com.example.domains.new2"